 ## 実践編

## モルかウサか判定AI

このノートでは、モルモットとウサギを見分ける簡単な機械学習モデルを作成する。

題材は「耳の長さ」と「体重」。

まずは手作業でデータを作成し、

- データセットとは何か
- AIは何を見て判断するのか
- 機械学習がどのように分類を行うのか

を理解することを目的とする。

---

## 今回のデータ

In [3]:
import pandas as pd

data = {
    "耳の長さ":[5, 6, 2, 3],
    "体重":[1.5, 1.7, 0.9, 1.0],
    "種類":["ウサギ","ウサギ","モルモット","モルモット"]
}

df = pd.DataFrame(data)
df

   耳の長さ   体重     種類
0     5  1.5    ウサギ
1     6  1.7    ウサギ
2     2  0.9  モルモット
3     3  1.0  モルモット

## 新入り

In [6]:
new_animal = {
    "耳の長さ": [4],
    "体重": [1.2]
}

new_df = pd.DataFrame(new_animal)
new_df

   耳の長さ   体重
0     4  1.2

この動物が

- ウサギなのか
- モルモットなのか

を予想していく。

---

## このプロジェクトで学ぶこと
1. データセット作成
1. pandasでデータ管理
1. KNN（近傍法）
1. ロジスティック回帰
1. モデル評価
1. 機械学習の考え方

---

## 人間　予想
ウサギ

理由：
耳の長さも体重も中間だが、少しウサギ寄りに見えるため。

※この予想が正しいとは限らない。
機械学習モデルとの比較を行う。